--<ScriptOptions statementTerminator=";"/>

CREATE TABLE SYSPERMS (
		UUID CHAR(36) NOT NULL,
		OBJECTTYPE VARCHAR(36) NOT NULL,
		OBJECTID CHAR(36) NOT NULL,
		PERMISSION CHAR(36) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		ISGRANTABLE CHAR(1) NOT NULL
	);

CREATE TABLE SYSTRIGGERS (
		TRIGGERID CHAR(36) NOT NULL,
		TRIGGERNAME VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		CREATIONTIMESTAMP TIMESTAMP NOT NULL,
		EVENT CHAR(1) NOT NULL,
		FIRINGTIME CHAR(1) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		STATE CHAR(1) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		WHENSTMTID CHAR(36),
		ACTIONSTMTID CHAR(36),
		REFERENCEDCOLUMNS null,
		TRIGGERDEFINITION LONG VARCHAR,
		REFERENCINGOLD null,
		REFERENCINGNEW null,
		OLDREFERENCINGNAME VARCHAR(128),
		NEWREFERENCINGNAME VARCHAR(128)
	);

CREATE TABLE SYSCOLUMNS (
		REFERENCEID CHAR(36) NOT NULL,
		COLUMNNAME VARCHAR(128) NOT NULL,
		COLUMNNUMBER INTEGER NOT NULL,
		COLUMNDATATYPE null NOT NULL,
		COLUMNDEFAULT null,
		COLUMNDEFAULTID CHAR(36),
		AUTOINCREMENTVALUE BIGINT,
		AUTOINCREMENTSTART BIGINT,
		AUTOINCREMENTINC BIGINT
	);

CREATE TABLE SYSDEPENDS (
		DEPENDENTID CHAR(36) NOT NULL,
		DEPENDENTFINDER null NOT NULL,
		PROVIDERID CHAR(36) NOT NULL,
		PROVIDERFINDER null NOT NULL
	);

CREATE TABLE SYSDUMMY1 (
		IBMREQD CHAR(1)
	);

CREATE TABLE SYSSTATEMENTS (
		STMTID CHAR(36) NOT NULL,
		STMTNAME VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		VALID null NOT NULL,
		TEXT LONG VARCHAR NOT NULL,
		LASTCOMPILED TIMESTAMP,
		COMPILATIONSCHEMAID CHAR(36),
		USINGTEXT LONG VARCHAR
	);

CREATE TABLE SYSSEQUENCES (
		SEQUENCEID CHAR(36) NOT NULL,
		SEQUENCENAME VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		SEQUENCEDATATYPE null NOT NULL,
		CURRENTVALUE BIGINT,
		STARTVALUE BIGINT NOT NULL,
		MINIMUMVALUE BIGINT NOT NULL,
		MAXIMUMVALUE BIGINT NOT NULL,
		INCREMENT BIGINT NOT NULL,
		CYCLEOPTION CHAR(1) NOT NULL
	);

CREATE TABLE SYSSTATISTICS (
		STATID CHAR(36) NOT NULL,
		REFERENCEID CHAR(36) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		CREATIONTIMESTAMP TIMESTAMP NOT NULL,
		TYPE CHAR(1) NOT NULL,
		VALID null NOT NULL,
		COLCOUNT INTEGER NOT NULL,
		STATISTICS null NOT NULL
	);

CREATE TABLE SYSCONSTRAINTS (
		CONSTRAINTID CHAR(36) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		CONSTRAINTNAME VARCHAR(128) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		STATE CHAR(1) NOT NULL,
		REFERENCECOUNT INTEGER NOT NULL
	);

CREATE TABLE SYSCOLPERMS (
		COLPERMSID CHAR(36) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		COLUMNS null NOT NULL
	);

CREATE TABLE SYSSCHEMAS (
		SCHEMAID CHAR(36) NOT NULL,
		SCHEMANAME VARCHAR(128) NOT NULL,
		AUTHORIZATIONID VARCHAR(128) NOT NULL
	);

CREATE TABLE SYSROUTINEPERMS (
		ROUTINEPERMSID CHAR(36) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		ALIASID CHAR(36) NOT NULL,
		GRANTOPTION CHAR(1) NOT NULL
	);

CREATE TABLE BET (
		IDBET INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 11),
		IDUSER INTEGER,
		IDQUOTE INTEGER,
		BETAMOUNT INTEGER,
		TIMESTAMP TIMESTAMP
	);

CREATE TABLE SYSTABLES (
		TABLEID CHAR(36) NOT NULL,
		TABLENAME VARCHAR(128) NOT NULL,
		TABLETYPE CHAR(1) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		LOCKGRANULARITY CHAR(1) NOT NULL
	);

CREATE TABLE SYSCHECKS (
		CONSTRAINTID CHAR(36) NOT NULL,
		CHECKDEFINITION LONG VARCHAR NOT NULL,
		REFERENCEDCOLUMNS null NOT NULL
	);

CREATE TABLE SYSCONGLOMERATES (
		SCHEMAID CHAR(36) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		CONGLOMERATENUMBER BIGINT NOT NULL,
		CONGLOMERATENAME VARCHAR(128),
		ISINDEX null NOT NULL,
		DESCRIPTOR null,
		ISCONSTRAINT null,
		CONGLOMERATEID CHAR(36) NOT NULL
	);

CREATE TABLE SYSVIEWS (
		TABLEID CHAR(36) NOT NULL,
		VIEWDEFINITION LONG VARCHAR NOT NULL,
		CHECKOPTION CHAR(1) NOT NULL,
		COMPILATIONSCHEMAID CHAR(36)
	);

CREATE TABLE SYSROLES (
		UUID CHAR(36) NOT NULL,
		ROLEID VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		WITHADMINOPTION CHAR(1) NOT NULL,
		ISDEF CHAR(1) NOT NULL
	);

CREATE TABLE USERS (
		IDUSER INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 3),
		USERNAME VARCHAR(45),
		PASSWORD VARCHAR(45),
		LASTSEEN DATE,
		CREDIT INTEGER,
		ROLE VARCHAR(45)
	);

CREATE TABLE PLAYER (
		IDUSER INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 4),
		USERNAME VARCHAR(45) NOT NULL,
		PASSWORD VARCHAR(45),
		LASTSEEN DATE,
		ROLE VARCHAR(45)
	);

CREATE TABLE SYSALIASES (
		ALIASID CHAR(36) NOT NULL,
		ALIAS VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36),
		JAVACLASSNAME LONG VARCHAR NOT NULL,
		ALIASTYPE CHAR(1) NOT NULL,
		NAMESPACE CHAR(1) NOT NULL,
		SYSTEMALIAS null NOT NULL,
		ALIASINFO null,
		SPECIFICNAME VARCHAR(128) NOT NULL
	);

CREATE TABLE SYSKEYS (
		CONSTRAINTID CHAR(36) NOT NULL,
		CONGLOMERATEID CHAR(36) NOT NULL
	);

CREATE TABLE SYSUSERS (
		USERNAME VARCHAR(128) NOT NULL,
		HASHINGSCHEME VARCHAR(32672) NOT NULL,
		PASSWORD VARCHAR(32672) NOT NULL,
		LASTMODIFIED TIMESTAMP NOT NULL
	);

CREATE TABLE QUOTE (
		IDQUOTE INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 10),
		QUOTEVERSION INTEGER,
		IDEVENT INTEGER,
		VALUE INTEGER,
		OUTCOME VARCHAR(45),
		TIMESTAMP TIMESTAMP
	);

CREATE TABLE SYSTABLEPERMS (
		TABLEPERMSID CHAR(36) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		SELECTPRIV CHAR(1) NOT NULL,
		DELETEPRIV CHAR(1) NOT NULL,
		INSERTPRIV CHAR(1) NOT NULL,
		UPDATEPRIV CHAR(1) NOT NULL,
		REFERENCESPRIV CHAR(1) NOT NULL,
		TRIGGERPRIV CHAR(1) NOT NULL
	);

CREATE TABLE SYSFILES (
		FILEID CHAR(36) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		FILENAME VARCHAR(128) NOT NULL,
		GENERATIONID BIGINT NOT NULL
	);

CREATE TABLE EVENT (
		IDEVENTE INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 7),
		EVENTNAME VARCHAR(45),
		OUTCOME VARCHAR(45)
	);

CREATE TABLE SYSFOREIGNKEYS (
		CONSTRAINTID CHAR(36) NOT NULL,
		CONGLOMERATEID CHAR(36) NOT NULL,
		KEYCONSTRAINTID CHAR(36) NOT NULL,
		DELETERULE CHAR(1) NOT NULL,
		UPDATERULE CHAR(1) NOT NULL
	);

CREATE UNIQUE INDEX SYSCONGLOMERATES_INDEX2 ON SYSCONGLOMERATES (CONGLOMERATENAME ASC, SCHEMAID ASC);

CREATE UNIQUE INDEX SYSTRIGGERS_INDEX1 ON SYSTRIGGERS (TRIGGERID ASC);

CREATE INDEX SYSCONGLOMERATES_INDEX3 ON SYSCONGLOMERATES (TABLEID ASC);

CREATE UNIQUE INDEX SYSSEQUENCES_INDEX1 ON SYSSEQUENCES (SEQUENCEID ASC);

CREATE UNIQUE INDEX SYSTRIGGERS_INDEX2 ON SYSTRIGGERS (TRIGGERNAME ASC, SCHEMAID ASC);

CREATE UNIQUE INDEX SYSKEYS_INDEX1 ON SYSKEYS (CONSTRAINTID ASC);

CREATE UNIQUE INDEX SQL150206171930100 ON USERS (IDUSER ASC);

CREATE UNIQUE INDEX SYSCOLUMNS_INDEX1 ON SYSCOLUMNS (REFERENCEID ASC, COLUMNNAME ASC);

CREATE INDEX SYSCONSTRAINTS_INDEX3 ON SYSCONSTRAINTS (TABLEID ASC);

CREATE INDEX SYSPERMS_INDEX2 ON SYSPERMS (OBJECTID ASC);

CREATE UNIQUE INDEX SYSFILES_INDEX1 ON SYSFILES (FILENAME ASC, SCHEMAID ASC);

CREATE UNIQUE INDEX SQL150206125246880 ON QUOTE (IDQUOTE ASC);

CREATE UNIQUE INDEX SYSTABLEPERMS_INDEX1 ON SYSTABLEPERMS (GRANTEE ASC, TABLEID ASC, GRANTOR ASC);

CREATE INDEX SYSCOLUMNS_INDEX2 ON SYSCOLUMNS (COLUMNDEFAULTID ASC);

CREATE UNIQUE INDEX SYSCHECKS_INDEX1 ON SYSCHECKS (CONSTRAINTID ASC);

CREATE UNIQUE INDEX SYSCONSTRAINTS_INDEX2 ON SYSCONSTRAINTS (CONSTRAINTNAME ASC, SCHEMAID ASC);

CREATE INDEX SYSTABLEPERMS_INDEX3 ON SYSTABLEPERMS (TABLEID ASC);

CREATE UNIQUE INDEX SYSSCHEMAS_INDEX1 ON SYSSCHEMAS (SCHEMANAME ASC);

CREATE UNIQUE INDEX SYSTABLES_INDEX2 ON SYSTABLES (TABLEID ASC);

CREATE UNIQUE INDEX SYSFILES_INDEX2 ON SYSFILES (FILEID ASC);

CREATE UNIQUE INDEX SYSTABLES_INDEX1 ON SYSTABLES (TABLENAME ASC, SCHEMAID ASC);

CREATE UNIQUE INDEX SYSVIEWS_INDEX1 ON SYSVIEWS (TABLEID ASC);

CREATE UNIQUE INDEX SYSCONSTRAINTS_INDEX1 ON SYSCONSTRAINTS (CONSTRAINTID ASC);

CREATE INDEX SYSROUTINEPERMS_INDEX3 ON SYSROUTINEPERMS (ALIASID ASC);

CREATE INDEX SYSFOREIGNKEYS_INDEX2 ON SYSFOREIGNKEYS (KEYCONSTRAINTID ASC);

CREATE UNIQUE INDEX SYSFOREIGNKEYS_INDEX1 ON SYSFOREIGNKEYS (CONSTRAINTID ASC);

CREATE UNIQUE INDEX SYSALIASES_INDEX3 ON SYSALIASES (SCHEMAID ASC, SPECIFICNAME ASC);

CREATE UNIQUE INDEX SYSROUTINEPERMS_INDEX1 ON SYSROUTINEPERMS (GRANTEE ASC, ALIASID ASC, GRANTOR ASC);

CREATE INDEX SYSSTATISTICS_INDEX1 ON SYSSTATISTICS (TABLEID ASC, REFERENCEID ASC);

CREATE UNIQUE INDEX SQL150206125809060 ON BET (IDBET ASC);

CREATE UNIQUE INDEX SYSUSERS_INDEX1 ON SYSUSERS (USERNAME ASC);

CREATE UNIQUE INDEX SQL150206125415830 ON EVENT (IDEVENTE ASC);

CREATE INDEX SYSDEPENDS_INDEX1 ON SYSDEPENDS (DEPENDENTID ASC);

CREATE UNIQUE INDEX SYSALIASES_INDEX1 ON SYSALIASES (SCHEMAID ASC, ALIAS ASC, NAMESPACE ASC);

CREATE UNIQUE INDEX SYSSTATEMENTS_INDEX1 ON SYSSTATEMENTS (STMTID ASC);

CREATE UNIQUE INDEX SYSCOLPERMS_INDEX1 ON SYSCOLPERMS (GRANTEE ASC, TABLEID ASC, TYPE ASC, GRANTOR ASC);

CREATE INDEX SQL150207141501760 ON BET (IDUSER ASC);

CREATE UNIQUE INDEX SYSTABLEPERMS_INDEX2 ON SYSTABLEPERMS (TABLEPERMSID ASC);

CREATE UNIQUE INDEX SYSALIASES_INDEX2 ON SYSALIASES (ALIASID ASC);

CREATE INDEX SYSROLES_INDEX2 ON SYSROLES (ROLEID ASC, ISDEF ASC);

CREATE INDEX SYSTRIGGERS_INDEX3 ON SYSTRIGGERS (TABLEID ASC, CREATIONTIMESTAMP ASC);

CREATE UNIQUE INDEX SYSSTATEMENTS_INDEX2 ON SYSSTATEMENTS (STMTNAME ASC, SCHEMAID ASC);

CREATE UNIQUE INDEX SYSPERMS_INDEX1 ON SYSPERMS (UUID ASC);

CREATE UNIQUE INDEX SYSROLES_INDEX3 ON SYSROLES (UUID ASC);

CREATE INDEX SQL150207141317010 ON QUOTE (IDEVENT ASC);

CREATE INDEX SYSDEPENDS_INDEX2 ON SYSDEPENDS (PROVIDERID ASC);

CREATE UNIQUE INDEX SYSSEQUENCES_INDEX2 ON SYSSEQUENCES (SCHEMAID ASC, SEQUENCENAME ASC);

CREATE INDEX SQL150207141430280 ON BET (IDQUOTE ASC);

CREATE INDEX SYSCONGLOMERATES_INDEX1 ON SYSCONGLOMERATES (CONGLOMERATEID ASC);

CREATE UNIQUE INDEX SYSSCHEMAS_INDEX2 ON SYSSCHEMAS (SCHEMAID ASC);

CREATE UNIQUE INDEX SYSPERMS_INDEX3 ON SYSPERMS (GRANTEE ASC, OBJECTID ASC, GRANTOR ASC);

CREATE INDEX SYSCOLPERMS_INDEX3 ON SYSCOLPERMS (TABLEID ASC);

CREATE UNIQUE INDEX SYSROLES_INDEX1 ON SYSROLES (ROLEID ASC, GRANTEE ASC, GRANTOR ASC);

CREATE UNIQUE INDEX SYSROUTINEPERMS_INDEX2 ON SYSROUTINEPERMS (ROUTINEPERMSID ASC);

CREATE UNIQUE INDEX SYSCOLPERMS_INDEX2 ON SYSCOLPERMS (COLPERMSID ASC);

ALTER TABLE QUOTE ADD CONSTRAINT SQL150206125246880 PRIMARY KEY (IDQUOTE);

ALTER TABLE BET ADD CONSTRAINT SQL150206125809060 PRIMARY KEY (IDBET);

ALTER TABLE EVENT ADD CONSTRAINT SQL150206125415830 PRIMARY KEY (IDEVENTE);

ALTER TABLE USERS ADD CONSTRAINT SQL150206171930100 PRIMARY KEY (IDUSER);

ALTER TABLE BET ADD CONSTRAINT SQL150207141501760 FOREIGN KEY (IDUSER)
	REFERENCES USERS (IDUSER);

ALTER TABLE BET ADD CONSTRAINT SQL150207141430280 FOREIGN KEY (IDQUOTE)
	REFERENCES QUOTE (IDQUOTE);

ALTER TABLE QUOTE ADD CONSTRAINT SQL150207141317010 FOREIGN KEY (IDEVENT)
	REFERENCES EVENT (IDEVENTE);

